apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mariadb

resources:
- mariadb.yaml

configMapGenerator:
  - name: mariadb-cm
    behavior: merge
    files:
      - maria-kube.cnf
      - expire-logs-days.cnf