apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
    app.kubernetes.io/component: mariadb
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/part-of: mariadb
namespace: mariadb

resources:
- mariadb.yaml

configMapGenerator:
  - name: mariadb-cm
    files:
      - maria-kube.cnf
      - expire-logs-days.cnf